### PR TITLE
Another whitespace fix

### PR DESCRIPTION
**Pull request by jakirkham**
This tacks on one more whitespace fix on top of PR ( https://github.com/conda-forge/conda-smithy/pull/192 ).

Noted an extra space got added to the end of one of the lines in the README. Went to strip it off and PR it here, but realized that it got added in `master`. Also, this branch had conflicts with `master` after PR ( https://github.com/conda-forge/conda-smithy/pull/196 ) had been merged. So, I resolved the merge conflicts here. After merging this, it should go smoothly into `conda-forge/master`.

### CODE REVIEW

**Comment by pelson** [comment]
@jakirkham - sorry about this, but I rebased my branch and looks like it doesn't merge too well. I wonder if all of the proposed changes have made it into conda-smithy or not (the diffs seem to suggest they have)

**Comment by jakirkham** [comment]
So, this was designed to resolve those merge conflicts. I can take another crack at it. Shouldn't take long.

**Comment by pelson** [comment]
Just as a heads up, I merged conda-forge#192, so best to target master of conda-smithy.

**Comment by jakirkham** [comment]
Ok, just noticed that. Thanks.

**Comment by jakirkham** [comment]
Yeah, so this merged fine for me locally. I'll add a PR.

**Comment by jakirkham** [comment]
Please see this PR ( https://github.com/conda-forge/conda-smithy/pull/219 ).

**Pull request closed without merging**
